{% set name = "starlette" %}
{% set version = "0.38.1" %}


package:
  name: {{ name|lower }}-recipe
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 890e89d9b1b367bad6fd11a6e191f40d03504df1ff55fd15674a3b35a122990e

build:
  number: 0
  noarch: python

outputs:
  - name: {{ name }}
    build:
      script: python -m pip install . --no-deps --no-build-isolation -vv
      noarch: python
    requirements:
      host:
        - hatchling
        - python >=3.8
        - pip
      run:
        - python >=3.8
        - anyio <5,>=3.4.0
        - typing_extensions >=3.10.0
    test:
      commands:
        - python -c "from starlette import *"

  - name: {{ name }}-full
    build:
      script: echo Nothing to do.
      noarch: python
    requirements:
      host:
        - hatchling
        - python >=3.8
        - pip
      run:
        - python >=3.8
        - {{ pin_subpackage('starlette', exact=True) }}
        - itsdangerous
        - jinja2
        - python-multipart >=0.0.7
        - pyyaml
        - httpx >=0.22.0
    test:
      commands:
        - python -c "from starlette import *"

about:
  home: https://www.starlette.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The little ASGI framework that shines.
  description: |
    Starlette is a lightweight [ASGI](https://asgi.readthedocs.io/en/latest/)
    framework/toolkit.

    It is ideal for building high performance asyncio services, and supports
    both HTTP and WebSockets.
  doc_url: https://www.starlette.io/
  dev_url: https://github.com/encode/starlette/

extra:
  recipe-maintainers:
    - carlodri
    - dgasmith
    - thewchan
