{% set name = "starlette" %}
{% set version = "0.13.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5abb66937fedf2fdc8d365a2b1dd9fc560aeb2b1ebf4266ffa639dbe6355c239

build:
  number: 0
  noarch: python

test:
  commands:
    - python -c "from starlette import *"

outputs:
  - name: {{ name }}-base
    build:
      noarch: python
    script: build_base.sh
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
    test:
      imports:
        - starlette

  - name: {{ name }}
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - {{ pin_subpackage('starlette-base', exact=True) }}
        - aiofiles
        - graphene
        - itsdangerous
        - jinja2
        - python-multipart
        - pyyaml
        - requests
        - ujson
    test:
      imports:
        - starlette

about:
  home: https://www.starlette.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The little ASGI framework that shines. ✨
  description: |
    Starlette is a lightweight [ASGI](https://asgi.readthedocs.io/en/latest/)
    framework/toolkit.

    It is ideal for building high performance asyncio services, and supports
    both HTTP and WebSockets.
  doc_url: https://www.starlette.io/
  dev_url: https://github.com/encode/starlette/

extra:
  recipe-maintainers:
    - carlodri
    - dgasmith
