{% set name = "starlette" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2d4b9d53b8b07bbb7097778662b84d937d574209f2b4f52aa12fd937b0cae3b8

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    # everything here below is in extras_require: 
    # move to an "optional requirements" field as 
    # soon as conda allows it
    - aiofiles
    - asyncpg
    - graphene
    - itsdangerous
    - jinja2
    - python-multipart
    - pyyaml
    - requests
    - sqlalchemy
    - ujson

test:
  imports:
    - starlette.responses
    - starlette.applications

about:
  home: https://www.starlette.io/
  license: BSD-3-Clause
  license_family: BSD
  # PR to include license_file in src distribution https://github.com/encode/starlette/pull/121
  license_file: /LICENSE.md
  summary: 'The little ASGI framework that shines. ✨'
  description: |
    Starlette is a lightweight [ASGI](https://asgi.readthedocs.io/en/latest/)
    framework/toolkit.

    It is ideal for building high performance asyncio services, and supports
    both HTTP and WebSockets.
  doc_url: https://www.starlette.io/
  dev_url: https://github.com/encode/starlette/

extra:
  recipe-maintainers:
    - carlodri
