{% set version = "0.45.1" %}

{% set PYTHON = PYTHON | default("$PYTHON") %}

package:
  name: starlette
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/starlette/starlette-{{ version }}.tar.gz
  sha256: a8ae1fa3b1ab7ca83a4abd77871921a13fb5aeaf4874436fb96c29dfcd4ecfa3

build:
  number: 0
  noarch: python
  script: python -m pip install . --no-deps --no-build-isolation -vv --disable-pip-version-check

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - anyio >=3.4.0,<5
    - python >={{ python_min }}
    - typing_extensions >=3.10.0

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - starlette
  commands:
    - pip check

outputs:
  - name: starlette

  - name: starlette-full
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('starlette', exact=True) }}
        - httpx >=0.27.0,<0.29.0
        - itsdangerous
        - jinja2
        - python-multipart >=0.0.18
        - pyyaml
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - starlette
      commands:
        - pip check

about:
  home: https://www.starlette.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The little ASGI framework that shines.
  description: |
    Starlette is a lightweight [ASGI](https://asgi.readthedocs.io/en/latest/)
    framework/toolkit.

    It is ideal for building high performance asyncio services, and supports
    both HTTP and WebSockets.
  doc_url: https://www.starlette.io/
  dev_url: https://github.com/encode/starlette/

extra:
  feedstock-name: starlette
  recipe-maintainers:
    - carlodri
    - dgasmith
    - thewchan
