schema_version: 1

context:
  version: "0.47.1"
  PYTHON: "\"PYTHON | default(\"$PYTHON\")\""

recipe:
  name: starlette
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/starlette/starlette-${{ version }}.tar.gz
  sha256: aef012dd2b6be325ffa16698f9dc533614fb1cebd593a906b90dc1025529a79b

build:
  number: 0
  noarch: python
  script: python -m pip install . --no-deps --no-build-isolation -vv --disable-pip-version-check

outputs:
  - package:
      name: starlette
    requirements:
      build:
        - if: build_platform != target_platform
          then:
            - python
            - cross-python_${{ target_platform }}
      host:
        - hatchling
        - pip
        - python ${{ python_min }}.*
      run:
        - anyio >=3.6.2,<5
        - python >=${{ python_min }}
        - typing_extensions >=4.10.0

    tests:
      - python:
          imports:
            - starlette
          pip_check: true
          python_version: ${{ python_min }}.*

  - package:
      name: starlette-full
    build:
      noarch: generic
    requirements:
      host:
        - hatchling
        - pip
        - python ${{ python_min }}.*
      run:
        - ${{ pin_subpackage('starlette', exact=True) }}
        - httpx >=0.27.0,<0.29.0
        - itsdangerous
        - jinja2
        - python-multipart >=0.0.18
        - pyyaml
    tests:
      - python:
          imports:
            - starlette
          pip_check: true
          python_version: ${{ python_min }}.*

about:
  license: BSD-3-Clause
  license_file: LICENSE.md
  summary: The little ASGI framework that shines.
  description: |
    Starlette is a lightweight [ASGI](https://asgi.readthedocs.io/en/latest/)
    framework/toolkit.

    It is ideal for building high performance asyncio services, and supports
    both HTTP and WebSockets.
  homepage: https://www.starlette.io/
  repository: https://github.com/encode/starlette/
  documentation: https://www.starlette.io/

extra:
  feedstock-name: starlette
  recipe-maintainers:
    - carlodri
    - dgasmith
    - thewchan
