# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.7.0"
  python_check_max: "3.14"

recipe:
  name: starlette
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/s/starlette/starlette-${{ version }}.tar.gz
  sha256: c79f74ea63cff761804fbbfb182f1e0b440c2d07b164d24700c5a1bab5d6ff5d

build:
  number: 0
  noarch: python

outputs:
  - package:
      name: starlette
    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check --check-build-dependencies
    requirements:
      host:
        - hatchling
        - pip
        - python ${{ python_min }}.*
      run:
        - anyio >=4,<5
        - python >=${{ python_min }}
        - typing_extensions >=4.10.0
    tests:
      - package_contents:
          strict: true
          site_packages:
            - starlette/**
            - starlette-${{ version }}.dist-info/**
      - python:
          imports: starlette
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*

  - package:
      name: starlette-full
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("starlette", exact=True) }}
        - httpx >=0.27.0,<0.29.0
        - httpx2 >=2.0.0
        - itsdangerous
        - jinja2
        - opentelemetry-api
        - python-multipart >=0.0.18
        - pyyaml
    tests:
      - python:
          imports: starlette
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
      - files:
          source:
            - tests/
        requirements:
          run:
            - python-blockbuster >=1.5.23
            - opentelemetry-sdk >=1.44.0
            - pytest >=9.1.1
            - coverage >=7.8.2
            - python ${{ python_min }}.*
            - trio >=0.34.0
            - backports.zstd
        script:
          - coverage run --source=starlette --branch -m pytest -vv --tb=long --color=yes
          - coverage report --show-missing --skip-covered --fail-under=100

about:
  license: BSD-3-Clause
  license_file: LICENSE.md
  summary: The little ASGI framework that shines.
  description: |
    Starlette is a lightweight [ASGI](https://asgi.readthedocs.io/en/latest/)
    framework/toolkit.

    It is ideal for building high performance asyncio services, and supports
    both HTTP and WebSockets.
  homepage: https://pypi.org/project/starlette
  repository: https://github.com/Kludex/starlette
  documentation: https://starlette.dev

extra:
  feedstock-name: starlette
  recipe-maintainers:
    - carlodri
    - dgasmith
    - thewchan
    - bollwyvl
