# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.47.3"
  python_check_max: "3.13"

recipe:
  name: starlette
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/starlette/starlette-${{ version }}.tar.gz
  sha256: 6bc94f839cc176c4858894f1f8908f0ab79dfec1a6b8402f6da9be26ebea52e9

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv --disable-pip-version-check

outputs:
  - package:
      name: starlette
    requirements:
      build:
        - if: build_platform != target_platform
          then:
            - python
            - cross-python_${{ target_platform }}
      host:
        - hatchling
        - pip
        - python ${{ python_min }}.*
      run:
        - anyio >=3.6.2,<5
        - python >=${{ python_min }}
        - typing_extensions >=4.10.0

    tests:
      - python:
          imports: starlette
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*

  - package:
      name: starlette-full
    build:
      noarch: generic
    requirements:
      host:
        - hatchling
        - pip
        - python ${{ python_min }}.*
      run:
        - ${{ pin_subpackage('starlette', exact=True) }}
        - httpx >=0.27.0,<0.29.0
        - itsdangerous
        - jinja2
        - python-multipart >=0.0.18
        - pyyaml
    tests:
      - python:
          imports: starlette
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*

about:
  license: BSD-3-Clause
  license_file: LICENSE.md
  summary: The little ASGI framework that shines.
  description: |
    Starlette is a lightweight [ASGI](https://asgi.readthedocs.io/en/latest/)
    framework/toolkit.

    It is ideal for building high performance asyncio services, and supports
    both HTTP and WebSockets.
  homepage: https://www.starlette.io/
  repository: https://github.com/encode/starlette/
  documentation: https://www.starlette.io/

extra:
  feedstock-name: starlette
  recipe-maintainers:
    - carlodri
    - dgasmith
    - thewchan
    - bollwyvl
