# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.0.0"
  python_check_max: "3.14"

recipe:
  name: starlette
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/starlette/starlette-${{ version }}.tar.gz
  sha256: 6a4beaf1f81bb472fd19ea9b918b50dc3a77a6f2e190a12954b25e6ed5eea149

build:
  number: 0
  noarch: python

outputs:
  - package:
      name: starlette
    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
    requirements:
      host:
        - hatchling
        - pip
        - python ${{ python_min }}.*
      run:
        - anyio >=3.6.2,<5
        - python >=${{ python_min }}
        - typing_extensions >=4.10.0
    tests:
      - python:
          imports: starlette
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*

  - package:
      name: starlette-full
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("starlette", exact=True) }}
        - httpx >=0.27.0,<0.29.0
        - itsdangerous
        - jinja2
        - python-multipart >=0.0.18
        - pyyaml
    tests:
      - python:
          imports: starlette
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
      - files:
          source:
            - tests/
        requirements:
          run:
            - mypy
            - pytest-cov
            - python ${{ python_min }}.*
            - trio
            - types-pyyaml
        script:
          - coverage run --source=starlette --branch -m pytest -vv --tb=long --color=yes
          - coverage report --show-missing --skip-covered --fail-under=100
          - mypy -p starlette

about:
  license: BSD-3-Clause
  license_file: LICENSE.md
  summary: The little ASGI framework that shines.
  description: |
    Starlette is a lightweight [ASGI](https://asgi.readthedocs.io/en/latest/)
    framework/toolkit.

    It is ideal for building high performance asyncio services, and supports
    both HTTP and WebSockets.
  homepage: https://pypi.org/project/starlette
  repository: https://github.com/Kludex/starlette
  documentation: https://www.starlette.io

extra:
  feedstock-name: starlette
  recipe-maintainers:
    - carlodri
    - dgasmith
    - thewchan
    - bollwyvl
